write name David Forgione in Team.md
hei-synd-225-sem/2020-sem pull request #11
Opened 2020-11-16 13:07 UTC by irdof

2020-11-16 13:17 UTC, metc requested changes

2020-11-16 13:17 UTC, metc commented on Team.md
> +FORGIONE. DAVID.
Do not use capital letters, please :)

2020-11-16 13:17 UTC, metc commented on Team.md
> +FORGIONE. DAVID.
Points should be removed as well.

2020-11-17 09:29 UTC, metc requested changes
Thanks for your contribution.
Please rebase (`git rebase`) your work on top of the latest `master` branch so I can merge your work. Thank you.

2020-11-17 12:01 UTC, irdof commented on Team.md
> +FORGIONE. DAVID.
Désolé je n'ai pas vu les messages, je le fais maintenant!

2020-11-19 08:16 UTC, closed without merging